name: carousel_extended
description: A Flutter Carousel Slider widget based on carousel_pro. Also support navigating sliders. 
version: 1.0.0+1
homepage: https://github.com/omidh28/flutter-carousel-extended

environment:
  sdk: '>=2.0.0 <3.0.0'
  flutter: ">=1.2.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
